# nat-gateway variables
variable "region" {}
variable "project_name" {}
variable "environment" {}
variable "costcenter" {}
variable "createdby" {}
variable "data_sensitivity" {}
variable "public_subnet_az1_id" {}
variable "internet_gateway" {}
variable "public_subnet_az2_id" {}
variable "vpc_id" {}
variable "private_appstream_subnet_az1_id" {}
variable "private_appstream_subnet_az2_id" {}
variable  "public_subnet_ids" {}
variable  "security_group_ids" {}
