# appstream variables
variable "project_name" {}
variable "environment" {}
variable "costcenter" {}
variable "createdby" {}
variable "owner" {}
variable "data_sensitivity" {}
variable "private_appstream_subnet_az1_id" {}
variable "private_appstream_subnet_az2_id" {}
variable "appstream_instance_type" {}
variable "appstream_image_name" {}
variable "private_subnet_ids" {}
variable "security_group_ids" {}
variable "iam_role_arn" {}
variable "appstream_usage_report_s3_bucket_name" {}
variable "appstream_usage_report_s3_bucket_arn" {}
variable "appstream_role_arn" {}
variable "vpce_id" {}